import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  await prisma.category.createMany({
    data: [
      {
        id: 1,
        name: "Produkty sypkie",
        iconUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=160&q=80",
        imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80",
        description: "Kasze, ryże, mąki i płatki z certyfikowanych upraw do codziennych posiłków.",
        exploreInfo: "Filtruj po typie ziarna, czasie gotowania i gramaturze.",
      },
      {
        id: 2,
        name: "Nabiał roślinny",
        iconUrl: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=160&q=80",
        imageUrl: "https://images.unsplash.com/photo-1478144592103-25e218a04891?auto=format&fit=crop&w=900&q=80",
        description: "Mleka, jogurty i napoje roślinne bez zbędnych dodatków.",
        exploreInfo: "Wybierz bazę (owies, migdał, soja) oraz warianty bez cukru.",
      },
      {
        id: 3,
        name: "Przetwory i miody",
        iconUrl: "https://images.unsplash.com/photo-1505575967455-40e256f73376?auto=format&fit=crop&w=160&q=80",
        imageUrl: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=900&q=80",
        description: "Konfitury, miody i pasty orzechowe słodzone naturalnie.",
        exploreInfo: "Sprawdź skład, rodzaj słodzika i pojemność słoika.",
      },
      {
        id: 4,
        name: "Przyprawy i dodatki",
        iconUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=160&q=80",
        imageUrl: "https://images.unsplash.com/photo-1464306076886-da185f6a9d4e?auto=format&fit=crop&w=900&q=80",
        description: "Suszone zioła, mieszanki przypraw, sól i dodatki w naturalnych wariantach.",
        exploreInfo: "Dobierz profil smaku oraz grubość mielenia.",
      },
      {
        id: 5,
        name: "Napoje",
        iconUrl: "https://images.unsplash.com/photo-1451748266019-10a91ca3d86c?auto=format&fit=crop&w=160&q=80",
        imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80",
        description: "Herbaty, kawy i napary z transparentnym pochodzeniem.",
        exploreInfo: "Sortuj po poziomie kofeiny i gramaturze opakowania.",
      },
      {
        id: 6,
        name: "Śniadania i przekąski",
        iconUrl: "https://images.unsplash.com/photo-1484981138541-3d074aa97716?auto=format&fit=crop&w=160&q=80",
        imageUrl: "https://images.unsplash.com/photo-1494390248081-4e521a5940db?auto=format&fit=crop&w=900&q=80",
        description: "Granole, musli i zdrowe batoniki na szybki zastrzyk energii.",
        exploreInfo: "Wybierz ulubioną bazę, dodatki i poziom słodkości.",
      },
    ],
  });

  await prisma.brand.createMany({
    data: [
      {
        id: 1,
        name: "EkoZiarno",
        imageUrl: "https://placehold.co/160x60/2d6b44/ffffff?text=EkoZiarno",
      },
      {
        id: 2,
        name: "Roślinna Farma",
        imageUrl: "https://placehold.co/160x60/398755/ffffff?text=Roslinna+Farma",
      },
      {
        id: 3,
        name: "Pasieka Leśna",
        imageUrl: "https://placehold.co/160x60/6bbd86/0f1510?text=Pasieka+Lesna",
      },
      {
        id: 4,
        name: "Zioła z Łąki",
        imageUrl: "https://placehold.co/160x60/a66f2a/0f1510?text=Ziola+z+Laki",
      },
      {
        id: 5,
        name: "Herbaciany Zakątek",
        imageUrl: "https://placehold.co/160x60/3c8e57/ffffff?text=Herbaciany+Zakatek",
      },
      {
        id: 6,
        name: "Śniadaniowa Pracownia",
        imageUrl: "https://placehold.co/160x60/2d6b44/ffffff?text=Sniadaniowa+Pracownia",
      },
    ],
  });

  await prisma.product.createMany({
    data: [
      {
        id: 1,
        brandId: 1,
        categoryId: 1,
        name: "Kasza jaglana bio 500 g",
        description: "Delikatna kasza jaglana z certyfikowanych upraw, bezglutenowa i lekka.",
        exploreInfo: "Świetna do dań na słodko i wytrawnie; pakowana w papierowy worek.",
        price: 6.5,
        discount: 0,
        stock: 40,
        imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 2,
        brandId: 1,
        categoryId: 1,
        name: "Ryż basmati pełnoziarnisty 1 kg",
        description: "Aromatyczny ryż basmati w wersji pełnoziarnistej, sypki po ugotowaniu.",
        exploreInfo: "Sprawdza się w kuchni indyjskiej i azjatyckiej; opakowanie 1 kg.",
        price: 12.2,
        discount: 0,
        stock: 36,
        imageUrl: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 3,
        brandId: 1,
        categoryId: 1,
        name: "Płatki owsiane górskie 1 kg",
        description: "Duże płatki owsiane, idealne do owsianki i wypieków.",
        exploreInfo: "Bez dodatku cukru, bogate w błonnik; szybkie gotowanie.",
        price: 7.4,
        discount: 0,
        stock: 58,
        imageUrl: "https://images.unsplash.com/photo-1484981138541-3d074aa97716?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 4,
        brandId: 1,
        categoryId: 1,
        name: "Mąka orkiszowa typ 650 1 kg",
        description: "Mąka z orkiszu do chleba, naleśników i ciast.",
        exploreInfo: "Mielona na kamieniach; delikatny orzechowy aromat.",
        price: 9.6,
        discount: 0,
        stock: 44,
        imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 5,
        brandId: 2,
        categoryId: 2,
        name: "Napój owsiany barista 1 l",
        description: "Kremowy napój owsiany do kawy i gotowania.",
        exploreInfo: "Łatwo się spienia, bez dodatku cukru.",
        price: 8.3,
        discount: 0,
        stock: 50,
        imageUrl: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 6,
        brandId: 2,
        categoryId: 2,
        name: "Jogurt kokosowy naturalny 400 g",
        description: "Gęsty jogurt kokosowy bez laktozy i konserwantów.",
        exploreInfo: "Idealny do owoców, musli i deserów.",
        price: 9.9,
        discount: 0,
        stock: 35,
        imageUrl: "https://images.unsplash.com/photo-1478144592103-25e218a04891?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 7,
        brandId: 2,
        categoryId: 2,
        name: "Napój migdałowy bez cukru 1 l",
        description: "Lekki napój migdałowy z krótkim składem.",
        exploreInfo: "Świetny do smoothie i płatków; bez dodatku cukru.",
        price: 8.8,
        discount: 1,
        stock: 46,
        imageUrl: "https://images.unsplash.com/photo-1478145046317-39f10e56b5e9?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 8,
        brandId: 3,
        categoryId: 3,
        name: "Miód lipowy 400 g",
        description: "Miód lipowy z pasiek leśnych, kremowy i aromatyczny.",
        exploreInfo: "Naturalna słodycz do herbat i wypieków.",
        price: 19.5,
        discount: 0,
        stock: 28,
        imageUrl: "https://images.unsplash.com/photo-1505575967455-40e256f73376?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 9,
        brandId: 3,
        categoryId: 3,
        name: "Konfitura malinowa 300 g",
        description: "Konfitura z malin, słodzona sokiem jabłkowym.",
        exploreInfo: "Dużo owoców i krótki skład; bez sztucznych dodatków.",
        price: 12.2,
        discount: 0,
        stock: 32,
        imageUrl: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 10,
        brandId: 3,
        categoryId: 3,
        name: "Masło orzechowe 100% 350 g",
        description: "Gładkie masło z prażonych orzechów arachidowych.",
        exploreInfo: "Bez soli i cukru; tylko orzechy.",
        price: 15.5,
        discount: 0,
        stock: 38,
        imageUrl: "https://images.unsplash.com/photo-1505576391880-b3f9d713dc4f?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 11,
        brandId: 4,
        categoryId: 4,
        name: "Mieszanka curry 80 g",
        description: "Aromatyczna mieszanka przypraw z kurkumą i kuminem.",
        exploreInfo: "Podkręca dania warzywne, zupy i sosy.",
        price: 6.2,
        discount: 0,
        stock: 60,
        imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 12,
        brandId: 4,
        categoryId: 4,
        name: "Sól morska gruboziarnista 1 kg",
        description: "Naturalna sól morska, grube kryształki.",
        exploreInfo: "Do mielenia i gotowania; bez antyzbrylaczy.",
        price: 5.8,
        discount: 0,
        stock: 80,
        imageUrl: "https://images.unsplash.com/photo-1457414104202-9f8cb462fdd2?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 13,
        brandId: 4,
        categoryId: 4,
        name: "Zioła prowansalskie 50 g",
        description: "Klasyczna mieszanka ziół do pieczeni i warzyw.",
        exploreInfo: "Bazylia, tymianek, rozmaryn i oregano.",
        price: 5.1,
        discount: 0,
        stock: 55,
        imageUrl: "https://images.unsplash.com/photo-1464306076886-da185f6a9d4e?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 14,
        brandId: 5,
        categoryId: 5,
        name: "Herbata ziołowa relaks 80 g",
        description: "Ziołowa kompozycja z melisą, rumiankiem i lipą.",
        exploreInfo: "Idealna na spokojny wieczór; liście luzem.",
        price: 9.4,
        discount: 0,
        stock: 48,
        imageUrl: "https://images.unsplash.com/photo-1451748266019-10a91ca3d86c?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 15,
        brandId: 5,
        categoryId: 5,
        name: "Kawa ziarnista fair trade 250 g",
        description: "Średnio palona arabika z certyfikatem fair trade.",
        exploreInfo: "Nutny czekolady i orzechów; świeżo palona.",
        price: 18.9,
        discount: 0,
        stock: 34,
        imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 16,
        brandId: 6,
        categoryId: 6,
        name: "Granola orzechowa 400 g",
        description: "Chrupalna granola z orzechami i miodem.",
        exploreInfo: "Bez rafinowanego cukru; świetna do jogurtu.",
        price: 14.2,
        discount: 0.7,
        stock: 42,
        imageUrl: "https://images.unsplash.com/photo-1484981138541-3d074aa97716?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 17,
        brandId: 6,
        categoryId: 6,
        name: "Musli z owocami 500 g",
        description: "Musli z suszonymi owocami i pestkami.",
        exploreInfo: "Szybkie śniadanie na co dzień.",
        price: 13.5,
        discount: 0,
        stock: 46,
        imageUrl: "https://images.unsplash.com/photo-1494390248081-4e521a5940db?auto=format&fit=crop&w=900&q=80",
      },
      {
        id: 18,
        brandId: 6,
        categoryId: 6,
        name: "Baton daktylowy kakao 45 g",
        description: "Miękki baton z daktyli i kakao.",
        exploreInfo: "Prosty skład, idealny na przekąskę.",
        price: 4.2,
        discount: 0,
        stock: 90,
        imageUrl: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=80",
      },
    ],
  });

  await prisma.user.upsert({
    where: { email: "eko@example.com" },
    update: {},
    create: {
      email: "eko@example.com",
      firstName: "Eko",
      password: await bcrypt.hash("Password123!", 10),
      phone: "+48111222333",
      country: "Poland",
    },
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
